version: '3.6'

services:
  ftth:
    container_name: ftth-tracker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      # - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      PORT: 3000
